### ISSUE TITLE
Calibration question

### ISSUE THREAD

**Issue by rnunziata** [alejocb/dpptam#37]
I run the ros bag file ( lab_unizar.bag ) and get a very nice dense point cloud right off. but when I use my web cam it takes a really long time to get anything to show up (just not finding enough key frames?) When it does start to create a point cloud it is very slow to add new points. Is the a calibration issue or a web cam issue. How can I tell what to look at to resolve this kind of behavior. Thank you for any help you can offer.

**Comment by rnunziata** [comment]
was not establishing base plane using ...  web cam usage issue.

**Comment by Sachet12345** [comment]
HI, I am facing the same problem. Could you tell me the solution?
